package com.more.sdk.entity;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_email
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    private String memberEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_email
     *
     * @return the value of member.member_email
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_email
     *
     * @param memberEmail the value for member.member_email
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail == null ? null : memberEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_id
     *
     * @return the value of member.user_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_id
     *
     * @param userId the value for member.user_id
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}