package com.more.sdk.entity;

import java.util.Date;

public class PermissionDefinition {
    private Integer memberLevel;
    private String permission;
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_definition.member_level
     *
     * @return the value of permission_definition.member_level
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public Integer getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_definition.member_level
     *
     * @param memberLevel the value for permission_definition.member_level
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setMemberLevel(Integer memberLevel) {
        this.memberLevel = memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_definition.permission
     *
     * @return the value of permission_definition.permission
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_definition.permission
     *
     * @param permission the value for permission_definition.permission
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_definition.create_date
     *
     * @return the value of permission_definition.create_date
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_definition.create_date
     *
     * @param createDate the value for permission_definition.create_date
     *
     * @mbggenerated Wed Jan 17 17:06:24 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}