package com.more.sdk.entity;

import java.util.Date;

public class Sdk {
    private Integer sdkId;
    private String sdkOs;
    private String sdkOwner;
    private String sdkName;
    private String sdkDesc;
    private String sdkFile;
    private String sdkDoc;
    private String sdkIcon;
    private Integer sdkState;
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_id
     *
     * @return the value of sdk.sdk_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Integer getSdkId() {
        return sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_id
     *
     * @param sdkId the value for sdk.sdk_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkId(Integer sdkId) {
        this.sdkId = sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_os
     *
     * @return the value of sdk.sdk_os
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkOs() {
        return sdkOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_os
     *
     * @param sdkOs the value for sdk.sdk_os
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkOs(String sdkOs) {
        this.sdkOs = sdkOs == null ? null : sdkOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_owner
     *
     * @return the value of sdk.sdk_owner
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkOwner() {
        return sdkOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_owner
     *
     * @param sdkOwner the value for sdk.sdk_owner
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkOwner(String sdkOwner) {
        this.sdkOwner = sdkOwner == null ? null : sdkOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_name
     *
     * @return the value of sdk.sdk_name
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkName() {
        return sdkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_name
     *
     * @param sdkName the value for sdk.sdk_name
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkName(String sdkName) {
        this.sdkName = sdkName == null ? null : sdkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_desc
     *
     * @return the value of sdk.sdk_desc
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkDesc() {
        return sdkDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_desc
     *
     * @param sdkDesc the value for sdk.sdk_desc
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkDesc(String sdkDesc) {
        this.sdkDesc = sdkDesc == null ? null : sdkDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_file
     *
     * @return the value of sdk.sdk_file
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkFile() {
        return sdkFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_file
     *
     * @param sdkFile the value for sdk.sdk_file
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkFile(String sdkFile) {
        this.sdkFile = sdkFile == null ? null : sdkFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_doc
     *
     * @return the value of sdk.sdk_doc
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkDoc() {
        return sdkDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_doc
     *
     * @param sdkDoc the value for sdk.sdk_doc
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkDoc(String sdkDoc) {
        this.sdkDoc = sdkDoc == null ? null : sdkDoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_icon
     *
     * @return the value of sdk.sdk_icon
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getSdkIcon() {
        return sdkIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_icon
     *
     * @param sdkIcon the value for sdk.sdk_icon
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkIcon(String sdkIcon) {
        this.sdkIcon = sdkIcon == null ? null : sdkIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.sdk_state
     *
     * @return the value of sdk.sdk_state
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Integer getSdkState() {
        return sdkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.sdk_state
     *
     * @param sdkState the value for sdk.sdk_state
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkState(Integer sdkState) {
        this.sdkState = sdkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk.create_date
     *
     * @return the value of sdk.create_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk.create_date
     *
     * @param createDate the value for sdk.create_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}