package com.more.sdk.entity;

import java.util.Date;

public class SdkAuthDuration {
    private Integer authId;
    private String appId;
    private Integer sdkId;
    private Date startDate;
    private Date endDate;
    private Date createDate;
    private Date updateDate;
    private Integer updater;
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.auth_id
     *
     * @param authId the value for sdk_auth_duration.auth_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.app_id
     *
     * @return the value of sdk_auth_duration.app_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.app_id
     *
     * @param appId the value for sdk_auth_duration.app_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.sdk_id
     *
     * @return the value of sdk_auth_duration.sdk_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Integer getSdkId() {
        return sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.sdk_id
     *
     * @param sdkId the value for sdk_auth_duration.sdk_id
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setSdkId(Integer sdkId) {
        this.sdkId = sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.start_date
     *
     * @return the value of sdk_auth_duration.start_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.start_date
     *
     * @param startDate the value for sdk_auth_duration.start_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.end_date
     *
     * @return the value of sdk_auth_duration.end_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.end_date
     *
     * @param endDate the value for sdk_auth_duration.end_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.create_date
     *
     * @return the value of sdk_auth_duration.create_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.create_date
     *
     * @param createDate the value for sdk_auth_duration.create_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.update_date
     *
     * @return the value of sdk_auth_duration.update_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.update_date
     *
     * @param updateDate the value for sdk_auth_duration.update_date
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_auth_duration.updater
     *
     * @return the value of sdk_auth_duration.updater
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_auth_duration.updater
     *
     * @param updater the value for sdk_auth_duration.updater
     *
     * @mbggenerated Tue Jan 16 17:37:14 CST 2018
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }
}