package com.more.sdk.entity;

import java.util.Date;

public class SdkGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group.id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group.node_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group.node_type
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer nodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group.id
     *
     * @return the value of sdk_group.id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group.id
     *
     * @param id the value for sdk_group.id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group.group_id
     *
     * @return the value of sdk_group.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group.group_id
     *
     * @param groupId the value for sdk_group.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group.node_id
     *
     * @return the value of sdk_group.node_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group.node_id
     *
     * @param nodeId the value for sdk_group.node_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group.node_type
     *
     * @return the value of sdk_group.node_type
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group.node_type
     *
     * @param nodeType the value for sdk_group.node_type
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group.create_date
     *
     * @return the value of sdk_group.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group.create_date
     *
     * @param createDate the value for sdk_group.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}