package com.more.sdk.entity.api.plus;

import java.util.Date;

import com.more.sdk.entity.Sdk;

public class SdkGroupDefinitionPlus extends Sdk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.category
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.group_state
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer groupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.group_level
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer groupLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.start_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.end_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.update_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_group_definition.updater
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    private Integer updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.group_id
     *
     * @return the value of sdk_group_definition.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.group_id
     *
     * @param groupId the value for sdk_group_definition.group_id
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.category
     *
     * @return the value of sdk_group_definition.category
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.category
     *
     * @param category the value for sdk_group_definition.category
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.group_state
     *
     * @return the value of sdk_group_definition.group_state
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getGroupState() {
        return groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.group_state
     *
     * @param groupState the value for sdk_group_definition.group_state
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setGroupState(Integer groupState) {
        this.groupState = groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.group_level
     *
     * @return the value of sdk_group_definition.group_level
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getGroupLevel() {
        return groupLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.group_level
     *
     * @param groupLevel the value for sdk_group_definition.group_level
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setGroupLevel(Integer groupLevel) {
        this.groupLevel = groupLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.start_date
     *
     * @return the value of sdk_group_definition.start_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.start_date
     *
     * @param startDate the value for sdk_group_definition.start_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.end_date
     *
     * @return the value of sdk_group_definition.end_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.end_date
     *
     * @param endDate the value for sdk_group_definition.end_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.create_date
     *
     * @return the value of sdk_group_definition.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.create_date
     *
     * @param createDate the value for sdk_group_definition.create_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.update_date
     *
     * @return the value of sdk_group_definition.update_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.update_date
     *
     * @param updateDate the value for sdk_group_definition.update_date
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_group_definition.updater
     *
     * @return the value of sdk_group_definition.updater
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_group_definition.updater
     *
     * @param updater the value for sdk_group_definition.updater
     *
     * @mbggenerated Sun Mar 04 23:14:46 CST 2018
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }
}